version: 0.2

phases:
  install:
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - npm install
#  pre_build:
#    commands:
#      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build:$REACT_APP_STAGE
      - aws s3 sync build s3://ilingu-platform-$REACT_APP_STAGE
      - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths /
  post_build:
    commands:
      - echo Build completed on `date`
      - ./aws-config/bin/test_if_test.sh
