export const GET_ERROR_MESSAGE = "GET_ERROR_MESSAGE";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

export const REQUEST_USER_GROUPS = "REQUEST_USER_GROUPS";
export const RECEIVE_USER_GROUPS = "RECEIVE_USER_GROUPS";

// userInfo actions
export const FETCH_TEACHER_DATA_START = "FETCH_TEACHER_DATA_START";
export const FETCH_TEACHER_DATA_RETURN = "FETCH_TEACHER_DATA_RETURN";
export const REQUEST_TEACHER = "REQUEST_TEACHER";
export const RECEIVE_TEACHER = "RECEIVE_TEACHER";
export const REQUEST_TEACHER_LESSONS = "REQUEST_TEACHER_LESSONS";
export const RECEIVE_TEACHER_LESSONS = "RECEIVE_TEACHER_LESSONS";
export const REQUEST_TEACHER_AVAILABILITIES = "REQUEST_TEACHER_AVAILABILITIES";
export const RECEIVE_TEACHER_AVAILABILITIES = "RECEIVE_TEACHER_AVAILABILITIES";
export const UPDATE_TEACHER_START = "UPDATE_TEACHER_START";
export const UPDATE_TEACHER_RETURN = "UPDATE_TEACHER_RETURN";

// studentInfo actions
export const REQUEST_STUDENT = "REQUEST_STUDENT";
export const RECEIVE_STUDENT = "RECEIVE_STUDENT";
export const REQUEST_AVATAR_URL = "REQUEST_AVATAR_URL";
export const RECEIVE_AVATAR_URL = "RECEIVE_AVATAR_URL";
export const REQUEST_COURSES = "REQUEST_COURSES";
export const RECEIVE_COURSES = "RECEIVE_COURSES";
export const REQUEST_ENROLMENTS = "REQUEST_ENROLMENTS";
export const RECEIVE_ENROLMENTS = "RECEIVE_ENROLMENTS";
export const ADDING_TRIAL_QUESTIONNAIRE = "ADDING_TRIAL_QUESTIONNAIRE";
export const ADDED_TRIAL_QUESTIONNAIRE = "ADDED_TRIAL_QUESTIONNAIRE";

export const UPLOADING_AVATAR = "UPLOADING_AVATAR";
export const UPLOADED_AVATAR = "UPLOADED_AVATAR";

export const REQUEST_BILLING_PROFILE = "REQUEST_BILLING_PROFILE";
export const RECEIVE_BILLING_PROFILE = "RECEIVE_BILLING_PROFILE";
export const REQUEST_SOURCES = "REQUEST_SOURCES";
export const RECEIVE_SOURCES = "RECEIVE_SOURCES";
export const ATTACHING_SOURCE = "ATTACHING_SOURCE";
export const ATTACHED_SOURCE = "ATTACHED_SOURCE";
export const DELETING_SOURCE = "DELETING_SOURCE";
export const DELETED_SOURCE = "DELETED_SOURCE";
export const CHANGING_DEFAULT_SOURCE = "CHANGING_DEFAULT_SOURCE";
export const CHANGED_DEFAULT_SOURCE = "CHANGED_DEFAULT_SOURCE";

// general user actions
export const ADDING_ADDRESS = "ADDING_ADDRESS";
export const ADDED_ADDRESS = "ADDED_ADDRESS";
export const REQUEST_ADDRESSES = "REQUEST_ADDRESSES";
export const RECEIVE_ADDRESSES = "RECEIVE_ADDRESSES";
export const CHANGING_DEFAULT_ADDRESSES = "CHANGING_DEFAULT_ADDRESSES";
export const CHANGED_DEFAULT_ADDRESSES = "CHANGED_DEFAULT_ADDRESSES";

// courseInfo actions
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const REQUEST_TEACHERS = "REQUEST_TEACHERS";
export const RECEIVE_TEACHERS = "RECEIVE_TEACHERS";
export const CREATING_COURSE = "CREATING_COURSE";
export const CREATED_COURSE = "CREATED_COURSE";
export const CREATING_ENROLMENT = "CREATING_ENROLMENT";
export const CREATED_ENROLMENT = "CREATED_ENROLMENT";
export const CREATING_LESSON = "CREATING_LESSON";
export const CREATED_LESSON = "CREATED_LESSON";

// adminInfo actions
// students actions
export const GET_STUDENT_START = "GET_STUDENT_START";
export const GET_STUDENT_RETURN = "GET_STUDENT_RETURN";
export const UPDATE_STUDENT_START = "UPDATE_STUDENT_START";
export const UPDATE_STUDENT_RETURN = "UPDATE_STUDENT_RETURN";
export const LIST_STUDENTS_START = "LIST_STUDENTS_START";
export const LIST_STUDENTS_RETURN = "LIST_STUDENTS_RETURN";
// teachers actions
export const GET_TEACHER_START = "GET_TEACHER_START";
export const GET_TEACHER_RETURN = "GET_TEACHER_RETURN";
// export const UPDATE_TEACHER_START = "UPDATE_TEACHER_START";
// export const UPDATE_TEACHER_RETURN = "UPDATE_TEACHER_RETURN";
export const LIST_TEACHERS_START = "LIST_TEACHERS_START";
export const LIST_TEACHERS_RETURN = "LIST_TEACHERS_RETURN";
// courses actions
export const GET_COURSE_START = "GET_COURSE_START";
export const GET_COURSE_RETURN = "GET_COURSE_RETURN";
export const UPDATE_COURSE_START = "UPDATE_COURSE_START";
export const UPDATE_COURSE_RETURN = "UPDATE_COURSE_RETURN";
export const LIST_COURSES_START = "LIST_COURSES_START";
export const LIST_COURSES_RETURN = "LIST_COURSES_RETURN";
export const DELETE_COURSE_START = "DELETE_COURSE_START";
export const DELETE_COURSE_RETURN = "DELETE_COURSE_RETURN";
// enrolments actions
export const CREATE_ENROLMENT_START = "CREATE_ENROLMENT_START";
export const CREATE_ENROLMENT_RETURN = "CREATE_ENROLMENT_RETURN";
export const GET_ENROLMENT_START = "GET_ENROLMENT_START";
export const GET_ENROLMENT_RETURN = "GET_ENROLMENT_RETURN";
export const UPDATE_ENROLMENT_START = "UPDATE_ENROLMENT_START";
export const UPDATE_ENROLMENT_RETURN = "UPDATE_ENROLMENT_RETURN";
export const LIST_ENROLMENTS_START = "LIST_ENROLMENTS_START";
export const LIST_ENROLMENTS_RETURN = "LIST_ENROLMENTS_RETURN";
// lessons actions
export const GET_LESSON_START = "GET_LESSON_START";
export const GET_LESSON_RETURN = "GET_LESSON_RETURN";
export const UPDATE_LESSON_START = "UPDATE_LESSON_START";
export const UPDATE_LESSON_RETURN = "UPDATE_LESSON_RETURN";
export const LIST_LESSONS_START = "LIST_LESSONS_START";
export const LIST_LESSONS_RETURN = "LIST_LESSONS_RETURN";
// products actions
export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START";
export const CREATE_PRODUCT_RETURN = "CREATE_PRODUCT_RETURN";
export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_RETURN = "GET_PRODUCT_RETURN";
export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_RETURN = "UPDATE_PRODUCT_RETURN";
export const LIST_PRODUCTS_START = "LIST_PRODUCTS_START";
export const LIST_PRODUCTS_RETURN = "LIST_PRODUCTS_RETURN";

// teacherInfo actions
export const LIST_LESSONS_BY_TEACHER_ID_START = "LIST_LESSONS_BY_TEACHER_ID_START";
export const LIST_LESSONS_BY_TEACHER_ID_RETURN = "LIST_LESSONS_BY_TEACHER_ID_RETURN";
export const LIST_COURSES_BY_TEACHER_ID_START = " LIST_COURSES_BY_TEACHER_ID_START";
export const LIST_COURSES_BY_TEACHER_ID_RETURN = "LIST_COURSES_BY_TEACHER_ID_RETURN";